Web/src/DNAWorker.Web.Mvc/Areas/AppAreaName/Models/Users/CreateOrEditUserModalViewModel.cs
using System.Collections.Generic;
using System.Linq;
using Abp.AutoMapper;
using DNAWorker.Authorization.Users.Dto;
using DNAWorker.Security;
using DNAWorker.Web.Areas.AppAreaName.Models.Common;

namespace DNAWorker.Web.Areas.AppAreaName.Models.Users
{
    [AutoMapFrom(typeof(GetUserForEditOutput))]
    public class CreateOrEditUserModalViewModel : GetUserForEditOutput, IOrganizationUnitsEditViewModel
    {
        public bool CanChangeUserName
        {
            get { return User.UserName != Authorization.Users.User.AdminUserName; }
        }

        public int AssignedRoleCount
        {
            get { return Roles.Count(r => r.IsAssigned); }
        }

        public bool IsEditMode
        {
            get { return User.Id.HasValue; }
        }

        public PasswordComplexitySetting PasswordComplexitySetting { get; set; }

        public CreateOrEditUserModalViewModel(GetUserForEditOutput output)
        {
            output.MapTo(this);
        }
    }
}

Web/src/DNAWorker.Web.Mvc/Areas/AppAreaName/Models/Users/UserLoginAttemptModalViewModel.cs
using System.Collections.Generic;
using DNAWorker.Authorization.Users.Dto;

namespace DNAWorker.Web.Areas.AppAreaName.Models.Users
{
    public class UserLoginAttemptModalViewModel
    {
        public List<UserLoginAttemptDto> LoginAttempts { get; set; }
    }
}

Web/src/DNAWorker.Web.Mvc/Areas/AppAreaName/Models/Users/UserPermissionsEditViewModel.cs
using Abp.AutoMapper;
using DNAWorker.Authorization.Users;
using DNAWorker.Authorization.Users.Dto;
using DNAWorker.Web.Areas.AppAreaName.Models.Common;

namespace DNAWorker.Web.Areas.AppAreaName.Models.Users
{
    [AutoMapFrom(typeof(GetUserPermissionsForEditOutput))]
    public class UserPermissionsEditViewModel : GetUserPermissionsForEditOutput, IPermissionsEditViewModel
    {
        public User User { get; private set; }

        public UserPermissionsEditViewModel(GetUserPermissionsForEditOutput output, User user)
        {
            User = user;
            output.MapTo(this);
        }
    }
}

Web/src/DNAWorker.Web.Mvc/Areas/AppAreaName/Models/Users/UsersViewModel.cs
using System.Collections.Generic;
using Abp.Application.Services.Dto;
using DNAWorker.Security;

namespace DNAWorker.Web.Areas.AppAreaName.Models.Users
{
    public class UsersViewModel
    {
        public string FilterText { get; set; }

        public List<ComboboxItemDto> Permissions { get; set; }

        public List<ComboboxItemDto> Roles { get; set; }
    }
}

Web/src/DNAWorker.Web.Mvc/Areas/AppAreaName/Controllers/UsersController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Abp.Application.Services.Dto;
using Abp.AspNetCore.Mvc.Authorization;
using Microsoft.AspNetCore.Mvc;
using DNAWorker.Authorization;
using DNAWorker.Authorization.Permissions;
using DNAWorker.Authorization.Roles;
using DNAWorker.Authorization.Roles.Dto;
using DNAWorker.Authorization.Users;
using DNAWorker.Security;
using DNAWorker.Web.Areas.AppAreaName.Models.Users;
using DNAWorker.Web.Controllers;

namespace DNAWorker.Web.Areas.AppAreaName.Controllers
{
    [Area("AppAreaName")]
    [AbpMvcAuthorize(AppPermissions.Pages_Administration_Users)]
    public class UsersController : DNAWorkerControllerBase
    {
        private readonly IUserAppService _userAppService;
        private readonly UserManager _userManager;
        private readonly IUserLoginAppService _userLoginAppService;
        private readonly IRoleAppService _roleAppService;
        private readonly IPermissionAppService _permissionAppService;
        private readonly IPasswordComplexitySettingStore _passwordComplexitySettingStore;

        public UsersController(
            IUserAppService userAppService,
            UserManager userManager,
            IUserLoginAppService userLoginAppService,
            IRoleAppService roleAppService,
            IPermissionAppService permissionAppService,
            IPasswordComplexitySettingStore passwordComplexitySettingStore)
        {
            _userAppService = userAppService;
            _userManager = userManager;
            _userLoginAppService = userLoginAppService;
            _roleAppService = roleAppService;
            _permissionAppService = permissionAppService;
            _passwordComplexitySettingStore = passwordComplexitySettingStore;
        }

        public async Task<ActionResult> Index()
        {
            var roles = new List<ComboboxItemDto>();
            var permissions = _permissionAppService.GetAllPermissions()
                                                    .Items
                                                    .Select(p => new ComboboxItemDto(p.Name, new string('-', p.Level * 2) + " " + p.DisplayName))
                                                    .ToList();

            if (IsGranted(AppPermissions.Pages_Administration_Roles))
            {
                var getRolesOutput = await _roleAppService.GetRoles(new GetRolesInput());
                roles = getRolesOutput.Items.Select(r => new ComboboxItemDto(r.Id.ToString(), r.DisplayName)).ToList();
            }

            roles.Insert(0, new ComboboxItemDto("", ""));
            permissions.Insert(0, new ComboboxItemDto("", ""));

            var model = new UsersViewModel
            {
                FilterText = Request.Query["filterText"],
                Roles = roles,
                Permissions = permissions
            };

            return View(model);
        }

        [AbpMvcAuthorize(AppPermissions.Pages_Administration_Users_Create, AppPermissions.Pages_Administration_Users_Edit)]
        public async Task<PartialViewResult> CreateOrEditModal(long? id)
        {
            var output = await _userAppService.GetUserForEdit(new NullableIdDto<long> { Id = id });
            var viewModel = new CreateOrEditUserModalViewModel(output)
            {
                PasswordComplexitySetting = await _passwordComplexitySettingStore.GetSettingsAsync()
            };

            return PartialView("_CreateOrEditModal", viewModel);
        }

        [AbpMvcAuthorize(AppPermissions.Pages_Administration_Users_ChangePermissions)]
        public async Task<PartialViewResult> PermissionsModal(long id)
        {
            var user = await _userManager.GetUserByIdAsync(id);
            var output = await _userAppService.GetUserPermissionsForEdit(new EntityDto<long>(id));
            var viewModel = new UserPermissionsEditViewModel(output, user);

            return PartialView("_PermissionsModal", viewModel);
        }

        public async Task<PartialViewResult> LoginAttemptsModal()
        {
            var output = await _userLoginAppService.GetRecentUserLoginAttempts();
            var model = new UserLoginAttemptModalViewModel
            {
                LoginAttempts = output.Items.ToList()
            };
            return PartialView("_LoginAttemptsModal", model);
        }
    }
}

Web/src/DNAWorker.Web.Mvc/Controllers/ProfileController.cs
using System;
using System.Threading.Tasks;
using Abp;
using Abp.AspNetCore.Mvc.Authorization;
using Abp.AspNetZeroCore.Net;
using Abp.Auditing;
using Abp.Domain.Uow;
using Abp.Extensions;
using Abp.Runtime.Session;
using Microsoft.AspNetCore.Mvc;
using DNAWorker.Authorization.Users;
using DNAWorker.Friendships;
using DNAWorker.Storage;

namespace DNAWorker.Web.Controllers
{
    [AbpMvcAuthorize]
    [DisableAuditing]
    public class ProfileController : ProfileControllerBase
    {
        private readonly UserManager _userManager;
        private readonly IBinaryObjectManager _binaryObjectManager;
        private readonly IFriendshipManager _friendshipManager;

        public ProfileController(
                UserManager userManager,
                IBinaryObjectManager binaryObjectManager,
                IAppFolders appFolders,
                IFriendshipManager friendshipManager
            ) : base(
                appFolders
            )
        {
            _userManager = userManager;
            _binaryObjectManager = binaryObjectManager;
            _friendshipManager = friendshipManager;
        }

        public async Task<FileResult> GetProfilePicture()
        {
            var user = await _userManager.GetUserByIdAsync(AbpSession.GetUserId());
            if (user.ProfilePictureId == null)
            {
                return GetDefaultProfilePicture();
            }

            return await GetProfilePictureById(user.ProfilePictureId.Value);
        }

        public async Task<FileResult> GetProfilePictureById(string id = "")
        {
            if (id.IsNullOrEmpty())
            {
                return GetDefaultProfilePicture();
            }

            return await GetProfilePictureById(Guid.Parse(id));
        }

        [UnitOfWork]
        public virtual async Task<FileResult> GetFriendProfilePictureById(long userId, int? tenantId, string id = "")
        {
            if (id.IsNullOrEmpty() ||
                await _friendshipManager.GetFriendshipOrNullAsync(AbpSession.ToUserIdentifier(), new UserIdentifier(tenantId, userId)) == null)
            {
                return GetDefaultProfilePicture();
            }

            using (CurrentUnitOfWork.SetTenantId(tenantId))
            {
                return await GetProfilePictureById(Guid.Parse(id));
            }
        }

        private FileResult GetDefaultProfilePicture()
        {
            return File(
                @"Common\Images\default-profile-picture.png",
                MimeTypeNames.ImagePng
            );
        }

        private async Task<FileResult> GetProfilePictureById(Guid profilePictureId)
        {
            var file = await _binaryObjectManager.GetOrNullAsync(profilePictureId);
            if (file == null)
            {
                return GetDefaultProfilePicture();
            }

            return File(file.Bytes, MimeTypeNames.ImageJpeg);
        }
    }
}

Web/src/DNAWorker.Web.Mvc/Areas/AppAreaName/Views/Users/Index.cshtml
@using System.Threading.Tasks
@using Abp.Application.Services.Dto
@using Abp.Json
@using DNAWorker.Authorization
@using DNAWorker.Web.Areas.AppAreaName.Models.Users
@using DNAWorker.Web.Areas.AppAreaName.Startup
@model UsersViewModel
@{
    ViewBag.CurrentPageName = AppAreaNamePageNames.Common.Users;
}
@section Styles
{
    <link rel="stylesheet" abp-href="/view-resources/Areas/AppAreaName/Views/Users/Index.css" asp-append-version="true" />
}
@section Scripts
{
    <script abp-src="/view-resources/Areas/AppAreaName/Views/_Bundles/user-list.js" asp-append-version="true"></script>
}
<div class="m-subheader">
    <div class="row align-items-center">
        <div class="mr-auto col-sm-12 col-md-6">
            <h3 class="m-subheader__title m-subheader__title--separator">
                <span>@L("Users")</span>
            </h3>
            <span class="m-section__sub">
                @L("UsersHeaderInfo")
            </span>
        </div>
        <div class="col-sm-12 col-md-6 text-right">
            <button id="ExportUsersToExcelButton" class="btn btn-outline-success"><i class="fa fa-file-excel-o"></i> @L("ExportToExcel")</button>
            @if (IsGranted(AppPermissions.Pages_Administration_Users_Create))
            {
                <button id="CreateNewUserButton" class="btn btn-primary"><i class="fa fa-plus"></i> @L("CreateNewUser")</button>
            }
        </div>
    </div>
</div>
<div class="m-content">
    <div class="m-portlet m-portlet--mobile">
        <div class="m-portlet__body">
            <div class="m-form m-form--label-align-right">
                <div class="row align-items-center m--margin-bottom-10">
                    <div class="col-xl-12">
                        <div class="form-group m-form__group align-items-center">
                            <div class="input-group">
                                <input type="text" id="UsersTableFilter" class="form-control m-input" placeholder="@L("SearchWithThreeDot")" value="@Model.FilterText">
                                <span class="input-group-btn">
                                    <button id="GetUsersButton" class="btn btn-primary" type="submit"><i class="flaticon-search-1" aria-label="@L("Search")"></i></button>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
                <div id="AdvacedAuditFiltersArea" style="display: none" class="row m--margin-bottom-10">
                    <div class="@(IsGranted(AppPermissions.Pages_Administration_Roles) ? "col-xl-6" : "col-xl-12")">
                        <div class="form-group">
                            @Html.DropDownList(
                                    "PermissionSelectionCombobox", Model.Permissions.Select(i => i.ToSelectListItem()),
                                    new
                                    {
                                        @class = "form-control selectpicker",
                                        data_live_search = "true",
                                        data_none_selected_text = L("FilterByPermission"),
                                        id = "PermissionSelectionCombo"
                                    })
                        </div>
                    </div>
                    @if (IsGranted(AppPermissions.Pages_Administration_Roles))
                    {
                        <div class="col-xl-6">
                            <div class="form-group">
                                @Html.DropDownList(
                                        "RoleSelectionCombobox", Model.Roles.Select(i => i.ToSelectListItem()),
                                        new
                                        {
                                            @class = "form-control selectpicker",
                                            data_live_search = "true",
                                            data_none_selected_text = L("FilterByRole"),
                                            id = "RoleSelectionCombo"
                                        })
                            </div>
                        </div>
                    }
                    <div class="col-xl-12 text-right">
                        <button id="RefreshUserListButton" class="btn btn-metal"><i class="fa fa-refresh"></i> @L("Refresh")</button>
                    </div>
                </div>
                <div class="row m--margin-bottom-10">
                    <div class="col-xl-12">
                        <span id="ShowAdvancedFiltersSpan" class="text-muted clickable-item"><i class="fa fa-angle-down"></i> @L("ShowAdvancedFilters")</span>
                        <span id="HideAdvancedFiltersSpan" class="text-muted clickable-item" style="display: none"><i class="fa fa-angle-up"></i> @L("HideAdvancedFilters")</span>
                    </div>
                </div>
            </div>
            <div class="row align-items-center">
                <table id="UsersTable" class="display table table-striped table-bordered table-hover dt-responsive nowrap">
                    <thead>
                        <tr>
                            <th>@L("Actions")</th>
                            <th>@L("UserName")</th>
                            <th>@L("Name")</th>
                            <th>@L("Surname")</th>
                            <th>@L("Roles")</th>
                            <th>@L("EmailAddress")</th>
                            <th>@L("EmailConfirm")</th>
                            <th>@L("Active")</th>
                            <th>@L("LastLoginTime")</th>
                            <th>@L("CreationTime")</th>
                        </tr>
                    </thead>
                </table>
            </div>

        </div>
    </div>
</div>

Web/src/DNAWorker.Web.Mvc/Areas/AppAreaName/Views/Users/_CreateOrEditModal.cshtml
@using Abp.Authorization.Users
@using Abp.Configuration
@using Abp.Json
@using Abp.Zero.Configuration
@using DNAWorker.Authorization.Users
@using DNAWorker.Web.Areas.AppAreaName.Models.Common.Modals
@using DNAWorker.Web.Areas.AppAreaName.Models.Users
@model CreateOrEditUserModalViewModel

<script>
    window.passwordComplexitySetting = @Html.Raw(Model.PasswordComplexitySetting.ToJsonString(indented: true));
</script>
@Html.Partial("~/Areas/AppAreaName/Views/Common/Modals/_ModalHeader.cshtml", new ModalHeaderViewModel(Model.IsEditMode ? (L("EditUser") + ": " + Model.User.UserName) : L("CreateNewUser")))

<div class="modal-body">
    <ul class="nav nav-tabs  m-tabs-line" role="tablist">
        <li class="nav-item m-tabs__item">
            <a href="#UserInformationsTab" class="nav-link m-tabs__link active" data-toggle="tab" role="tab">
                @L("UserInformations")
            </a>
        </li>
        <li class="nav-item m-tabs__item">
            <a href="#RolesTab" data-toggle="tab" role="tab" class="nav-link m-tabs__link">
                @L("Roles") <b class="badge badge-primary"><span id="assigned-role-count">@Model.AssignedRoleCount</span></b>
            </a>
        </li>
        <li class="nav-item m-tabs__item">
            <a href="#OrganizationUnitsTab" data-toggle="tab" role="tab" class="nav-link m-tabs__link">
                @L("OrganizationUnits")
            </a>
        </li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane active" id="UserInformationsTab" role="tabpanel">
            <form name="UserInformationsForm" role="form" novalidate class="form-validation">

                @if (Model.IsEditMode)
                {
                    <input type="hidden" name="Id" value="@Model.User.Id" />
                }

                <div class="row">
                    <div class="col-sm-3 text-center margin-top-15 margin-bottom-15">
                        @if (Model.ProfilePictureId.HasValue)
                        {
                            <img src="@Url.Action("GetProfilePictureById", "Profile", new { area = string.Empty })?id=@(Model.ProfilePictureId.Value)" width="128" height="128" class="img-thumbnail img-rounded user-edit-dialog-profile-image" />
                        }
                        else
                        {
                            <img src="@Url.Content("~/Common/Images/default-profile-picture.png")" width="128" height="128" class="img-thumbnail img-rounded user-edit-dialog-profile-image" />
                        }
                    </div>
                    <div class="col-sm-9">
                        <div class="form-group">
                            <label for="Name">@L("Name")</label>
                            <input id="Name" class="form-control" value="@Model.User.Name" type="text" name="Name" required maxlength="@DNAWorker.Authorization.Users.User.MaxNameLength">
                        </div>

                        <div class="form-group">
                            <label for="Surname">@L("Surname")</label>
                            <input id="Surname" type="text" name="Surname" class="form-control" value="@Model.User.Surname" required maxlength="@DNAWorker.Authorization.Users.User.MaxSurnameLength">
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <label for="EmailAddress">@L("EmailAddress")</label>
                    <input id="EmailAddress" type="email" name="EmailAddress" class="form-control" value="@Model.User.EmailAddress" required maxlength="@AbpUserBase.MaxEmailAddressLength">
                </div>

                <div class="form-group">
                    <label for="PhoneNumber">@L("PhoneNumber")</label>
                    <input id="PhoneNumber" type="text" name="PhoneNumber" class="form-control" value="@Model.User.PhoneNumber" maxlength="@UserConsts.MaxPhoneNumberLength">
                </div>

                <div class="form-group form-md-line-input form-md-floating-label">
                    <label for="UserName">@L("UserName")</label>
                    <input id="UserName" type="text" @Html.Raw(!Model.CanChangeUserName ? "disabled=\"disabled\"" : "") name="UserName" class="form-control" value="@Model.User.UserName" required maxlength="@AbpUserBase.MaxUserNameLength">
                    @if (!Model.CanChangeUserName)
                    {
                        <span class="help-block">@L("CanNotChangeAdminUserName")</span>
                    }
                </div>

                <div class="m-checkbox-list">
                    <label for="EditUser_SetRandomPassword" class="m-checkbox">
                        <input id="EditUser_SetRandomPassword" type="checkbox" name="SetRandomPassword" value="true" @Html.Raw(Model.IsEditMode ? "" : "checked=\"checked\"") />
                        @L("SetRandomPassword")
                        <span></span>
                    </label>
                </div>

                <div class="form-group user-password" style="@(Model.IsEditMode ? "display:block" : "display:none")">
                    <label for="EditUser_Password">@L("Password")</label>
                    <input id="EditUser_Password" type="password" name="Password" class="form-control" maxlength="@DNAWorker.Authorization.Users.User.MaxPlainPasswordLength" autocomplete="off" >
                </div>

                <div class="form-group user-password" style="@(Model.IsEditMode ? "display:block" : "display:none")">
                    <label for="PasswordRepeat">@L("PasswordRepeat")</label>
                    <input id="PasswordRepeat" type="password" name="PasswordRepeat" class="form-control" maxlength="@DNAWorker.Authorization.Users.User.MaxPlainPasswordLength" equalto="#EditUser_Password" autocomplete="off" >
                </div>

                <div class="m-checkbox-list">
                    <label for="EditUser_ShouldChangePasswordOnNextLogin" class="m-checkbox">
                        <input id="EditUser_ShouldChangePasswordOnNextLogin" type="checkbox" name="ShouldChangePasswordOnNextLogin" value="true" @Html.Raw(Model.User.ShouldChangePasswordOnNextLogin ? "checked=\"checked\"" : "")>
                        @L("ShouldChangePasswordOnNextLogin")
                        <span></span>
                    </label>
                    <label for="EditUser_SendActivationEmail" class="m-checkbox">
                        <input id="EditUser_SendActivationEmail" type="checkbox" name="SendActivationEmail" value="true" @Html.Raw(Model.IsEditMode ? "" : "checked=\"checked\"")>
                        @L("SendActivationEmail")
                        <span></span>
                    </label>
                    <label for="EditUser_IsActive" class="m-checkbox">
                        <input id="EditUser_IsActive" type="checkbox" name="IsActive" value="true" @Html.Raw(Model.User.IsActive ? "checked=\"checked\"" : "")>
                        @L("Active")
                        <span></span>
                    </label>
                    @if (SettingManager.GetSettingValue<bool>(AbpZeroSettingNames.UserManagement.TwoFactorLogin.IsEnabled))
                    {
                        <label for="EditUser_IsTwoFactorEnabled" class="m-checkbox">
                            <input id="EditUser_IsTwoFactorEnabled" type="checkbox" name="IsTwoFactorEnabled" value="true" @Html.Raw(Model.User.IsTwoFactorEnabled ? "checked=\"checked\"" : "")>
                            @L("IsTwoFactorEnabled")
                            <span></span>
                        </label>
                    }
                    @if (SettingManager.GetSettingValue<bool>(AbpZeroSettingNames.UserManagement.UserLockOut.IsEnabled))
                    {
                        <label for="EditUser_IsLockoutEnabled" data-toggle="tooltip" title="@L("IsLockoutEnabled_Hint")" class="m-checkbox">
                            <input id="EditUser_IsLockoutEnabled" type="checkbox" name="IsLockoutEnabled" value="true" @Html.Raw(Model.User.IsLockoutEnabled ? "checked=\"checked\"" : "")>
                            @L("IsLockoutEnabled")
                            <span></span>
                        </label>
                    }
                </div>

            </form>
        </div>
        <div class="tab-pane" id="RolesTab" role="tabpanel">
            <div class="user-role-checkbox-list">
                @foreach (var role in Model.Roles)
                {
                    <div class="m-checkbox-list">
                        <label for="EditUser_@(role.RoleName)" class="m-checkbox">
                            <input id="EditUser_@(role.RoleName)" type="checkbox" name="@(role.RoleName)" value="true" @Html.Raw(role.IsAssigned ? "checked=\"checked\"" : "")>
                            @role.RoleDisplayName
                            <span></span>
                        </label>
                    </div>
                }
            </div>
        </div>
        <div class="tab-pane" id="OrganizationUnitsTab" role="tabpanel">
            <div class="list-group">
                @Html.Partial("~/Areas/AppAreaName/Views/Common/_OrganizationTree.cshtml", Model)
            </div>
        </div>
    </div>
</div>

@Html.Partial("~/Areas/AppAreaName/Views/Common/Modals/_ModalFooterWithSaveAndCancel.cshtml")

Web/src/DNAWorker.Web.Mvc/Areas/AppAreaName/Views/Users/_LoginAttemptsModal.cshtml
@using Abp.Timing
@using DNAWorker.Web.Areas.AppAreaName.Models.Common.Modals
@using DNAWorker.Web.Areas.AppAreaName.Models.Users
@model UserLoginAttemptModalViewModel
@Html.Partial("~/Areas/AppAreaName/Views/Common/Modals/_ModalHeader.cshtml", new ModalHeaderViewModel(L("LoginAttempts")))
<div class="modal-body">
    <form id="loginAttemptsModalForm" class="form-horizontal">
        <div class="form-body">
            <div class="row">
                <div class="col-sm-12">
                    @foreach (var loginAttempt in Model.LoginAttempts)
                    {
                        <div class="m-alert m-alert--icon m-alert--icon-solid m-alert--outline alert @(loginAttempt.Result == "Success" ?"alert-success":"alert-danger")" role="alert">
                            <div class="m-alert__icon">
                                <img src="@(loginAttempt.Result == "Success" ?
                                                "/Profile/GetProfilePicture?v="+Clock.Now.Ticks :
                                                "/Common/Images/default-profile-picture.png")" class="m--img-rounded m--marginless m--img-centered" width="50" height="50">
                                <span></span>
                                <small class="label"> @(loginAttempt.Result == "Success" ? L("Success") : L("Failed")) </small>
                            </div>
                            <div class="m-alert__text">
                                @if (!string.IsNullOrEmpty(loginAttempt.ClientIpAddress))
                                {
                                    <div class="row">
                                        <label class="control-label col-sm-3 text-right">@L("IpAddress")</label>
                                        <div class="col-sm-9">
                                            <p class="form-control-static">
                                                @loginAttempt.ClientIpAddress
                                            </p>
                                        </div>
                                    </div>
                                }
                                @if (!string.IsNullOrEmpty(loginAttempt.ClientName))
                                {
                                    <div class="row">
                                        <label class="control-label col-sm-3 text-right">@L("Client")</label>
                                        <div class="col-sm-9">
                                            <p class="form-control-static">
                                                @loginAttempt.ClientName
                                            </p>
                                        </div>
                                    </div>
                                }
                                @if (!string.IsNullOrEmpty(loginAttempt.BrowserInfo))
                                {
                                    <div class="row">
                                        <label class="control-label col-sm-3 text-right">@L("Browser")</label>
                                        <div class="col-sm-9">
                                            <p class="form-control-static">
                                                @loginAttempt.BrowserInfo
                                            </p>
                                        </div>
                                    </div>
                                }
                                <div class="row">
                                    <label class="control-label col-sm-3 text-right">@L("Time")</label>
                                    <div class="col-sm-9">
                                        <p class="form-control-static login-attempt-date" data-date="@loginAttempt.CreationTime.ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")">

                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </form>
</div>
<div class="modal-footer">
    <button type="button" class="btn default close-button" data-dismiss="modal">@L("Close")</button>
</div>

Web/src/DNAWorker.Web.Mvc/Areas/AppAreaName/Views/Users/_PermissionsModal.cshtml
@using DNAWorker.Web.Areas.AppAreaName.Models.Common.Modals
@using DNAWorker.Web.Areas.AppAreaName.Models.Users
@model UserPermissionsEditViewModel

@Html.Partial("~/Areas/AppAreaName/Views/Common/Modals/_ModalHeader.cshtml", new ModalHeaderViewModel(L("Permissions") + " - " + Model.User.UserName))

<div class="modal-body">
    @Html.Partial("~/Areas/AppAreaName/Views/Common/_PermissionTree.cshtml", Model)
    
    <div class="note note-warning" style="margin-bottom: 0; margin-top: 15px">
        <em>@L("Note_RefreshPageForPermissionChanges")</em>
    </div>
</div>

<div class="modal-footer">
    <button type="button" class="btn btn-default pull-left reset-permissions-button" data-toggle="tooltip" title="@L("ResetPermissionsTooltip")" data-placement="top"><span>@L("ResetSpecialPermissions")</span></button>
    <button type="button" class="btn default close-button" data-dismiss="modal">@L("Cancel")</button>
    <button type="button" class="btn btn-primary save-button"><i class="fa fa-save"></i> <span>@L("Save")</span></button>
</div>